### ISSUE TITLE
extension dillo does not exist error on first installation, `manage.py dillo setup_db email ` command

### ISSUE THREAD

**Issue by trew100** [armadillica/dillo#103]
Hi 

I tring to install dillo
I follow after this doc installation https://dillo.space/docs/
and I got this error

```
python3 manage.py dillo setup_db my@email.com
Loading TLS certificates from /etc/ssl/certs/ca-certificates.crt
2019-04-15 14:34:26,890     INFO pillar.PillarServer Creating new instance from '/home/ubuntu/dillo/dillo'
2019-04-15 14:34:26,892  WARNING pillar.PillarServer STATIC_FILE_HASH is empty, generating random one
2019-04-15 14:34:26,892  WARNING pillar.PillarServer AUTH_TOKEN_HMAC_KEY not set, falling back to SECRET_KEY
2019-04-15 14:34:26,892  WARNING pillar.PillarServer Converting AUTH_TOKEN_HMAC_KEY to bytes
2019-04-15 14:34:26,910     INFO pillar.PillarServer Git revision b'b615888'
2019-04-15 14:34:26,912  WARNING pillar.PillarServer Sentry NOT configured.
2019-04-15 14:34:26,912     INFO pillar.PillarServer Setting up video encoding backend 'zencoder'
/home/ubuntu/.local/lib/python3.6/site-packages/flask_caching/__init__.py:188: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
2019-04-15 14:34:26,931     INFO pillar.PillarServer Configure translations
2019-04-15 14:34:26,932     INFO pillar.PillarServer Available languages: es, pt, en_US
2019-04-15 14:34:26,932     INFO pillar.PillarServer Loading extension dillo
/home/ubuntu/dillo/dillo/dillo/web/settings/forms.py:4: FlaskWTFDeprecationWarning: "flask_wtf.html5" will be removed in 1.0.  Import directly from "wtforms.fields.html5" and "wtforms.widgets.html5".
  from flask_wtf.html5 import URLField, EmailField
2019-04-15 14:34:27,091     INFO pillar.PillarServer Extension dillo: adding template path /home/ubuntu/dillo/dillo/dillo/templates
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from runserver import app
  File "/home/ubuntu/dillo/dillo/runserver.py", line 9, in <module>
    app.load_extension(dillo, None)
  File "/home/ubuntu/dillo/pillar/pillar/__init__.py", line 391, in load_extension
    tpath, pillar_extension.name)
ValueError: ('Template path %s for extension %s does not exist.', '/home/ubuntu/dillo/dillo/dillo/templates', 'dillo')
```

directory structure
```
~/dillo$ tree -L 1
.
├── dillo
├── pillar
└── pillar-python-sdk
```

**Comment by venomgfx** [comment]
By looking at the error seems that the templates folder is missing, did you `gulp` pillar and dillo before?

**Comment by trew100** [comment]
I need to run `glup`?

the documentation doesn't update?
https://dillo.space/docs/

**Comment by trew100** [comment]
Run `glup` resolve the problem

Maybe you can update the documentation
