### ISSUE TITLE
Error when running `manage.py setup setup_db email` for the first time

### ISSUE THREAD

**Issue by dfelinto** [armadillica/dillo#28]
I'm trying a fresh installation here, and I run into the following problem:
```
(...)
Creating group demo
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    cli.manager.run()
  File "/home/dfelinto/.virtualenvs/dillo/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/dfelinto/.virtualenvs/dillo/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/dfelinto/.virtualenvs/dillo/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/dfelinto/src/web-dev/pillar/pillar/cli/setup.py", line 37, in setup_db
    result, _, _, status = current_app.post_internal('users', user)
  File "/home/dfelinto/src/web-dev/pillar/pillar/__init__.py", line 769, in post_internal
    return post_internal(resource, payl=payl, skip_validation=skip_validation)[:4]
  File "/home/dfelinto/.virtualenvs/dillo/lib/python3.6/site-packages/eve/methods/post.py", line 280, in post_internal
    getattr(app, "on_inserted_%s" % resource)(documents)
  File "/home/dfelinto/.virtualenvs/dillo/lib/python3.6/site-packages/events/events.py", line 77, in __call__
    f(*a, **kw)
  File "/home/dfelinto/src/web-dev/dillo/dillo/api/users/hooks.py", line 49, in after_creating_users
    assign_to_user_main(user_doc)
  File "/home/dfelinto/src/web-dev/dillo/dillo/api/users/hooks.py", line 44, in assign_to_user_main
    add_user_to_group(user_id=user_doc['_id'], group_id=group_dillo_user_main['_id'])
TypeError: <flask_script.commands.Command object at 0x7f91a1338cc0>: 'NoneType' object is not subscriptable
```

**Comment by dfelinto** [comment]
Note to self: try "blender cloud"

**Comment by fsiddi** [comment]
This is a known issue, due to the fact that the `dillo_user_main` group does not exist. I have to make a command for setting up db for dillo, which wraps the `setup_db` of pillar.

**Comment by dfelinto** [comment]
Note to self: manually creating a `dillo_user_main` before running this command avoid this issue.

**Comment by socialwarespace** [comment]
@dfelinto You can write a detailed solution to the problem

**Comment by socialwarespace** [comment]
@fsiddi stopped at this point, you do not have a detailed manual for the installation?
