### ISSUE TITLE
config app

### ISSUE THREAD

**Issue by socialwarespace** [armadillica/dillo#64]
(blender-cloud) root@irk:/var/www/www-root/data/www/irk.media/dillo# python manage.py dillo setup_for_dillo default-project
Loading TLS certificates from /root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/requests/cacert.pem
2018-03-25 16:26:12,788     INFO pillar Pillar starting, debug=True
2018-03-25 16:26:12,789     INFO pillar.PillarServer Creating new instance from '/var/www/www-root/data/www/irk.media/dillo'
2018-03-25 16:26:12,791  WARNING pillar.PillarServer Converting AUTH_TOKEN_HMAC_KEY to bytes
2018-03-25 16:26:12,848     INFO pillar.PillarServer Git revision b'60084bf'
2018-03-25 16:26:12,852  WARNING pillar.PillarServer Sentry NOT configured.
2018-03-25 16:26:12,853     INFO pillar.PillarServer Setting up video encoding backend 'zencoder'
/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/flask_cache/jinja2ext.py:33: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  from flask.ext.cache import make_template_fragment_key
2018-03-25 16:26:12,875     INFO pillar.PillarServer Configure translations
2018-03-25 16:26:12,876     INFO pillar.PillarServer Available languages: ru_RU, es, en_US, pt
2018-03-25 16:26:12,877     INFO pillar.PillarServer Loading extension dillo
2018-03-25 16:26:13,091     INFO pillar.PillarServer Extension dillo: adding template path /var/www/www-root/data/www/irk.media/dillo/dillo/templates
2018-03-25 16:26:13,092     INFO pillar.PillarServer Extension dillo: adding translations path /var/www/www-root/data/www/irk.media/dillo/translations
2018-03-25 16:26:13,109     INFO pillar.PillarServer Using MongoDB database 'eve'
2018-03-25 16:26:13,110     INFO pillar.PillarServer Configuring Celery
2018-03-25 16:26:13,112     INFO pillar.PillarServer Pinging Celery workers
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from runserver import app
  File "/var/www/www-root/data/www/irk.media/dillo/runserver.py", line 10, in <module>
    app.process_extensions()
  File "/var/www/www-root/data/www/irk.media/pillar/pillar/__init__.py", line 571, in process_extensions
    self.finish_startup()
  File "/var/www/www-root/data/www/irk.media/pillar/pillar/__init__.py", line 702, in finish_startup
    self._config_celery()
  File "/var/www/www-root/data/www/irk.media/pillar/pillar/__init__.py", line 504, in _config_celery
    self.log.info('Response: %s', self.celery.control.ping())
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/celery/app/control.py", line 235, in ping
    timeout=timeout, **kwargs)
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/kombu/pidbox.py", line 304, in _broadcast
    chan = channel or self.connection.default_channel
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/kombu/connection.py", line 819, in default_channel
    self.connection
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/amqp/connection.py", line 294, in connect
    self.transport.connect()
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/amqp/transport.py", line 120, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/root/.virtualenvs/blender-cloud/lib/python3.6/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by fsiddi** [comment]
Thanks for trying out Dillo!
Please provide a description to the issue. We can't help based on log output. I also recommend you to tweak your Apache config *right now* as all your applications files are exposed to the public.

**Comment by socialwarespace** [comment]
Thank you, Apache has set up. Solved the previous problem.
I have one more at startup:

python manage.py dillo setup_for_dillo default-project

raise RuntimeError ('Project% s does not exist.'% project_url)
RuntimeError: Project irk.media does not exist.

What is the default-project parameter?

**Comment by fsiddi** [comment]
You need to create a default-project before initializing it for Dillo. We are going to work on the setup instructions to make this more clear.
